// Code generated by protoc-gen-go. DO NOT EDIT.
// source: barracuda.proto

package barracuda

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadBlobRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlobRequest) Reset()         { *m = ReadBlobRequest{} }
func (m *ReadBlobRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBlobRequest) ProtoMessage()    {}
func (*ReadBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d569ae014a1123a0, []int{0}
}

func (m *ReadBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlobRequest.Unmarshal(m, b)
}
func (m *ReadBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlobRequest.Marshal(b, m, deterministic)
}
func (m *ReadBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlobRequest.Merge(m, src)
}
func (m *ReadBlobRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBlobRequest.Size(m)
}
func (m *ReadBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlobRequest proto.InternalMessageInfo

func (m *ReadBlobRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ReadBlobResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlobResponse) Reset()         { *m = ReadBlobResponse{} }
func (m *ReadBlobResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlobResponse) ProtoMessage()    {}
func (*ReadBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d569ae014a1123a0, []int{1}
}

func (m *ReadBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlobResponse.Unmarshal(m, b)
}
func (m *ReadBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlobResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlobResponse.Merge(m, src)
}
func (m *ReadBlobResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlobResponse.Size(m)
}
func (m *ReadBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlobResponse proto.InternalMessageInfo

func (m *ReadBlobResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadBlobRequest)(nil), "barracuda.ReadBlobRequest")
	proto.RegisterType((*ReadBlobResponse)(nil), "barracuda.ReadBlobResponse")
}

func init() { proto.RegisterFile("barracuda.proto", fileDescriptor_d569ae014a1123a0) }

var fileDescriptor_d569ae014a1123a0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4a, 0x2c, 0x2a,
	0x4a, 0x4c, 0x2e, 0x4d, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x29, 0x73, 0xf1, 0x07, 0xa5, 0x26, 0xa6, 0x38, 0xe5, 0xe4, 0x27, 0x05, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0x98, 0x4a, 0x6a, 0x5c, 0x02, 0x08, 0x45, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42,
	0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x60, 0x65, 0x3c, 0x41, 0x60, 0xb6, 0x51, 0x10, 0x17, 0x27,
	0x48, 0x4d, 0x40, 0x51, 0x7e, 0x45, 0xa5, 0x90, 0x2b, 0x17, 0x07, 0x4c, 0x93, 0x90, 0x94, 0x1e,
	0xc2, 0x09, 0x68, 0xd6, 0x49, 0x49, 0x63, 0x95, 0x83, 0xd8, 0xa2, 0xc4, 0xe0, 0xa4, 0xce, 0x25,
	0x9c, 0x9c, 0x9f, 0xab, 0x87, 0xe6, 0x05, 0x27, 0x3e, 0x27, 0x98, 0x40, 0x00, 0x88, 0x1f, 0xc0,
	0x98, 0xc4, 0x06, 0x96, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x45, 0xbc, 0x43, 0x3c, 0xee,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlobProxyClient is the client API for BlobProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlobProxyClient interface {
	ReadBlob(ctx context.Context, in *ReadBlobRequest, opts ...grpc.CallOption) (*ReadBlobResponse, error)
}

type blobProxyClient struct {
	cc *grpc.ClientConn
}

func NewBlobProxyClient(cc *grpc.ClientConn) BlobProxyClient {
	return &blobProxyClient{cc}
}

func (c *blobProxyClient) ReadBlob(ctx context.Context, in *ReadBlobRequest, opts ...grpc.CallOption) (*ReadBlobResponse, error) {
	out := new(ReadBlobResponse)
	err := c.cc.Invoke(ctx, "/barracuda.BlobProxy/ReadBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobProxyServer is the server API for BlobProxy service.
type BlobProxyServer interface {
	ReadBlob(context.Context, *ReadBlobRequest) (*ReadBlobResponse, error)
}

// UnimplementedBlobProxyServer can be embedded to have forward compatible implementations.
type UnimplementedBlobProxyServer struct {
}

func (*UnimplementedBlobProxyServer) ReadBlob(ctx context.Context, req *ReadBlobRequest) (*ReadBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlob not implemented")
}

func RegisterBlobProxyServer(s *grpc.Server, srv BlobProxyServer) {
	s.RegisterService(&_BlobProxy_serviceDesc, srv)
}

func _BlobProxy_ReadBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobProxyServer).ReadBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/barracuda.BlobProxy/ReadBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobProxyServer).ReadBlob(ctx, req.(*ReadBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlobProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "barracuda.BlobProxy",
	HandlerType: (*BlobProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadBlob",
			Handler:    _BlobProxy_ReadBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barracuda.proto",
}
